# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

unordered_set_bucket_count_i <- function(x) {
    .Call(`_cppcontainers_unordered_set_bucket_count_i`, x)
}

unordered_set_bucket_count_d <- function(x) {
    .Call(`_cppcontainers_unordered_set_bucket_count_d`, x)
}

unordered_set_bucket_count_s <- function(x) {
    .Call(`_cppcontainers_unordered_set_bucket_count_s`, x)
}

unordered_set_bucket_count_b <- function(x) {
    .Call(`_cppcontainers_unordered_set_bucket_count_b`, x)
}

set_clear_i <- function(x) {
    invisible(.Call(`_cppcontainers_set_clear_i`, x))
}

set_clear_d <- function(x) {
    invisible(.Call(`_cppcontainers_set_clear_d`, x))
}

set_clear_s <- function(x) {
    invisible(.Call(`_cppcontainers_set_clear_s`, x))
}

set_clear_b <- function(x) {
    invisible(.Call(`_cppcontainers_set_clear_b`, x))
}

unordered_set_clear_i <- function(x) {
    invisible(.Call(`_cppcontainers_unordered_set_clear_i`, x))
}

unordered_set_clear_d <- function(x) {
    invisible(.Call(`_cppcontainers_unordered_set_clear_d`, x))
}

unordered_set_clear_s <- function(x) {
    invisible(.Call(`_cppcontainers_unordered_set_clear_s`, x))
}

unordered_set_clear_b <- function(x) {
    invisible(.Call(`_cppcontainers_unordered_set_clear_b`, x))
}

set_contains_i <- function(x, v) {
    .Call(`_cppcontainers_set_contains_i`, x, v)
}

set_contains_d <- function(x, v) {
    .Call(`_cppcontainers_set_contains_d`, x, v)
}

set_contains_s <- function(x, v) {
    .Call(`_cppcontainers_set_contains_s`, x, v)
}

set_contains_b <- function(x, v) {
    .Call(`_cppcontainers_set_contains_b`, x, v)
}

unordered_set_contains_i <- function(x, v) {
    .Call(`_cppcontainers_unordered_set_contains_i`, x, v)
}

unordered_set_contains_d <- function(x, v) {
    .Call(`_cppcontainers_unordered_set_contains_d`, x, v)
}

unordered_set_contains_s <- function(x, v) {
    .Call(`_cppcontainers_unordered_set_contains_s`, x, v)
}

unordered_set_contains_b <- function(x, v) {
    .Call(`_cppcontainers_unordered_set_contains_b`, x, v)
}

set_count_i <- function(x, v) {
    .Call(`_cppcontainers_set_count_i`, x, v)
}

set_count_d <- function(x, v) {
    .Call(`_cppcontainers_set_count_d`, x, v)
}

set_count_s <- function(x, v) {
    .Call(`_cppcontainers_set_count_s`, x, v)
}

set_count_b <- function(x, v) {
    .Call(`_cppcontainers_set_count_b`, x, v)
}

unordered_set_count_i <- function(x, v) {
    .Call(`_cppcontainers_unordered_set_count_i`, x, v)
}

unordered_set_count_d <- function(x, v) {
    .Call(`_cppcontainers_unordered_set_count_d`, x, v)
}

unordered_set_count_s <- function(x, v) {
    .Call(`_cppcontainers_unordered_set_count_s`, x, v)
}

unordered_set_count_b <- function(x, v) {
    .Call(`_cppcontainers_unordered_set_count_b`, x, v)
}

set_emplace_i <- function(x, v) {
    invisible(.Call(`_cppcontainers_set_emplace_i`, x, v))
}

set_emplace_d <- function(x, v) {
    invisible(.Call(`_cppcontainers_set_emplace_d`, x, v))
}

set_emplace_s <- function(x, v) {
    invisible(.Call(`_cppcontainers_set_emplace_s`, x, v))
}

set_emplace_b <- function(x, v) {
    invisible(.Call(`_cppcontainers_set_emplace_b`, x, v))
}

unordered_set_emplace_i <- function(x, v) {
    invisible(.Call(`_cppcontainers_unordered_set_emplace_i`, x, v))
}

unordered_set_emplace_d <- function(x, v) {
    invisible(.Call(`_cppcontainers_unordered_set_emplace_d`, x, v))
}

unordered_set_emplace_s <- function(x, v) {
    invisible(.Call(`_cppcontainers_unordered_set_emplace_s`, x, v))
}

unordered_set_emplace_b <- function(x, v) {
    invisible(.Call(`_cppcontainers_unordered_set_emplace_b`, x, v))
}

set_empty_i <- function(x) {
    .Call(`_cppcontainers_set_empty_i`, x)
}

set_empty_d <- function(x) {
    .Call(`_cppcontainers_set_empty_d`, x)
}

set_empty_s <- function(x) {
    .Call(`_cppcontainers_set_empty_s`, x)
}

set_empty_b <- function(x) {
    .Call(`_cppcontainers_set_empty_b`, x)
}

unordered_set_empty_i <- function(x) {
    .Call(`_cppcontainers_unordered_set_empty_i`, x)
}

unordered_set_empty_d <- function(x) {
    .Call(`_cppcontainers_unordered_set_empty_d`, x)
}

unordered_set_empty_s <- function(x) {
    .Call(`_cppcontainers_unordered_set_empty_s`, x)
}

unordered_set_empty_b <- function(x) {
    .Call(`_cppcontainers_unordered_set_empty_b`, x)
}

set_erase_i <- function(x, v) {
    invisible(.Call(`_cppcontainers_set_erase_i`, x, v))
}

set_erase_d <- function(x, v) {
    invisible(.Call(`_cppcontainers_set_erase_d`, x, v))
}

set_erase_s <- function(x, v) {
    invisible(.Call(`_cppcontainers_set_erase_s`, x, v))
}

set_erase_b <- function(x, v) {
    invisible(.Call(`_cppcontainers_set_erase_b`, x, v))
}

unordered_set_erase_i <- function(x, v) {
    invisible(.Call(`_cppcontainers_unordered_set_erase_i`, x, v))
}

unordered_set_erase_d <- function(x, v) {
    invisible(.Call(`_cppcontainers_unordered_set_erase_d`, x, v))
}

unordered_set_erase_s <- function(x, v) {
    invisible(.Call(`_cppcontainers_unordered_set_erase_s`, x, v))
}

unordered_set_erase_b <- function(x, v) {
    invisible(.Call(`_cppcontainers_unordered_set_erase_b`, x, v))
}

set_insert_i <- function(x, v) {
    invisible(.Call(`_cppcontainers_set_insert_i`, x, v))
}

set_insert_d <- function(x, v) {
    invisible(.Call(`_cppcontainers_set_insert_d`, x, v))
}

set_insert_s <- function(x, v) {
    invisible(.Call(`_cppcontainers_set_insert_s`, x, v))
}

set_insert_b <- function(x, v) {
    invisible(.Call(`_cppcontainers_set_insert_b`, x, v))
}

unordered_set_insert_i <- function(x, v) {
    invisible(.Call(`_cppcontainers_unordered_set_insert_i`, x, v))
}

unordered_set_insert_d <- function(x, v) {
    invisible(.Call(`_cppcontainers_unordered_set_insert_d`, x, v))
}

unordered_set_insert_s <- function(x, v) {
    invisible(.Call(`_cppcontainers_unordered_set_insert_s`, x, v))
}

unordered_set_insert_b <- function(x, v) {
    invisible(.Call(`_cppcontainers_unordered_set_insert_b`, x, v))
}

unordered_set_load_factor_i <- function(x) {
    .Call(`_cppcontainers_unordered_set_load_factor_i`, x)
}

unordered_set_load_factor_d <- function(x) {
    .Call(`_cppcontainers_unordered_set_load_factor_d`, x)
}

unordered_set_load_factor_s <- function(x) {
    .Call(`_cppcontainers_unordered_set_load_factor_s`, x)
}

unordered_set_load_factor_b <- function(x) {
    .Call(`_cppcontainers_unordered_set_load_factor_b`, x)
}

unordered_set_max_bucket_count_i <- function(x) {
    .Call(`_cppcontainers_unordered_set_max_bucket_count_i`, x)
}

unordered_set_max_bucket_count_d <- function(x) {
    .Call(`_cppcontainers_unordered_set_max_bucket_count_d`, x)
}

unordered_set_max_bucket_count_s <- function(x) {
    .Call(`_cppcontainers_unordered_set_max_bucket_count_s`, x)
}

unordered_set_max_bucket_count_b <- function(x) {
    .Call(`_cppcontainers_unordered_set_max_bucket_count_b`, x)
}

unordered_set_max_load_factor_i_get <- function(x) {
    .Call(`_cppcontainers_unordered_set_max_load_factor_i_get`, x)
}

unordered_set_max_load_factor_d_get <- function(x) {
    .Call(`_cppcontainers_unordered_set_max_load_factor_d_get`, x)
}

unordered_set_max_load_factor_s_get <- function(x) {
    .Call(`_cppcontainers_unordered_set_max_load_factor_s_get`, x)
}

unordered_set_max_load_factor_b_get <- function(x) {
    .Call(`_cppcontainers_unordered_set_max_load_factor_b_get`, x)
}

unordered_set_max_load_factor_i_set <- function(x, l) {
    invisible(.Call(`_cppcontainers_unordered_set_max_load_factor_i_set`, x, l))
}

unordered_set_max_load_factor_d_set <- function(x, l) {
    invisible(.Call(`_cppcontainers_unordered_set_max_load_factor_d_set`, x, l))
}

unordered_set_max_load_factor_s_set <- function(x, l) {
    invisible(.Call(`_cppcontainers_unordered_set_max_load_factor_s_set`, x, l))
}

unordered_set_max_load_factor_b_set <- function(x, l) {
    invisible(.Call(`_cppcontainers_unordered_set_max_load_factor_b_set`, x, l))
}

set_max_size_i <- function(x) {
    .Call(`_cppcontainers_set_max_size_i`, x)
}

set_max_size_d <- function(x) {
    .Call(`_cppcontainers_set_max_size_d`, x)
}

set_max_size_s <- function(x) {
    .Call(`_cppcontainers_set_max_size_s`, x)
}

set_max_size_b <- function(x) {
    .Call(`_cppcontainers_set_max_size_b`, x)
}

unordered_set_max_size_i <- function(x) {
    .Call(`_cppcontainers_unordered_set_max_size_i`, x)
}

unordered_set_max_size_d <- function(x) {
    .Call(`_cppcontainers_unordered_set_max_size_d`, x)
}

unordered_set_max_size_s <- function(x) {
    .Call(`_cppcontainers_unordered_set_max_size_s`, x)
}

unordered_set_max_size_b <- function(x) {
    .Call(`_cppcontainers_unordered_set_max_size_b`, x)
}

set_merge_i <- function(x, y) {
    invisible(.Call(`_cppcontainers_set_merge_i`, x, y))
}

set_merge_d <- function(x, y) {
    invisible(.Call(`_cppcontainers_set_merge_d`, x, y))
}

set_merge_s <- function(x, y) {
    invisible(.Call(`_cppcontainers_set_merge_s`, x, y))
}

set_merge_b <- function(x, y) {
    invisible(.Call(`_cppcontainers_set_merge_b`, x, y))
}

unordered_set_merge_i <- function(x, y) {
    invisible(.Call(`_cppcontainers_unordered_set_merge_i`, x, y))
}

unordered_set_merge_d <- function(x, y) {
    invisible(.Call(`_cppcontainers_unordered_set_merge_d`, x, y))
}

unordered_set_merge_s <- function(x, y) {
    invisible(.Call(`_cppcontainers_unordered_set_merge_s`, x, y))
}

unordered_set_merge_b <- function(x, y) {
    invisible(.Call(`_cppcontainers_unordered_set_merge_b`, x, y))
}

set_equal_i <- function(x, y) {
    .Call(`_cppcontainers_set_equal_i`, x, y)
}

set_equal_d <- function(x, y) {
    .Call(`_cppcontainers_set_equal_d`, x, y)
}

set_equal_s <- function(x, y) {
    .Call(`_cppcontainers_set_equal_s`, x, y)
}

set_equal_b <- function(x, y) {
    .Call(`_cppcontainers_set_equal_b`, x, y)
}

unordered_set_equal_i <- function(x, y) {
    .Call(`_cppcontainers_unordered_set_equal_i`, x, y)
}

unordered_set_equal_d <- function(x, y) {
    .Call(`_cppcontainers_unordered_set_equal_d`, x, y)
}

unordered_set_equal_s <- function(x, y) {
    .Call(`_cppcontainers_unordered_set_equal_s`, x, y)
}

unordered_set_equal_b <- function(x, y) {
    .Call(`_cppcontainers_unordered_set_equal_b`, x, y)
}

set_print_i <- function(x, use_n, n, reverse, use_from, from, use_to, to) {
    invisible(.Call(`_cppcontainers_set_print_i`, x, use_n, n, reverse, use_from, from, use_to, to))
}

set_print_d <- function(x, use_n, n, reverse, use_from, from, use_to, to) {
    invisible(.Call(`_cppcontainers_set_print_d`, x, use_n, n, reverse, use_from, from, use_to, to))
}

set_print_s <- function(x, use_n, n, reverse, use_from, from, use_to, to) {
    invisible(.Call(`_cppcontainers_set_print_s`, x, use_n, n, reverse, use_from, from, use_to, to))
}

set_print_b <- function(x, use_n, n, reverse, use_from, from, use_to, to) {
    invisible(.Call(`_cppcontainers_set_print_b`, x, use_n, n, reverse, use_from, from, use_to, to))
}

unordered_set_print_i <- function(x, n) {
    invisible(.Call(`_cppcontainers_unordered_set_print_i`, x, n))
}

unordered_set_print_d <- function(x, n) {
    invisible(.Call(`_cppcontainers_unordered_set_print_d`, x, n))
}

unordered_set_print_s <- function(x, n) {
    invisible(.Call(`_cppcontainers_unordered_set_print_s`, x, n))
}

unordered_set_print_b <- function(x, n) {
    invisible(.Call(`_cppcontainers_unordered_set_print_b`, x, n))
}

unordered_set_rehash_i <- function(x, n) {
    invisible(.Call(`_cppcontainers_unordered_set_rehash_i`, x, n))
}

unordered_set_rehash_d <- function(x, n) {
    invisible(.Call(`_cppcontainers_unordered_set_rehash_d`, x, n))
}

unordered_set_rehash_s <- function(x, n) {
    invisible(.Call(`_cppcontainers_unordered_set_rehash_s`, x, n))
}

unordered_set_rehash_b <- function(x, n) {
    invisible(.Call(`_cppcontainers_unordered_set_rehash_b`, x, n))
}

unordered_set_reserve_i <- function(x, n) {
    invisible(.Call(`_cppcontainers_unordered_set_reserve_i`, x, n))
}

unordered_set_reserve_d <- function(x, n) {
    invisible(.Call(`_cppcontainers_unordered_set_reserve_d`, x, n))
}

unordered_set_reserve_s <- function(x, n) {
    invisible(.Call(`_cppcontainers_unordered_set_reserve_s`, x, n))
}

unordered_set_reserve_b <- function(x, n) {
    invisible(.Call(`_cppcontainers_unordered_set_reserve_b`, x, n))
}

set_i <- function(v) {
    .Call(`_cppcontainers_set_i`, v)
}

set_d <- function(v) {
    .Call(`_cppcontainers_set_d`, v)
}

set_s <- function(v) {
    .Call(`_cppcontainers_set_s`, v)
}

set_b <- function(v) {
    .Call(`_cppcontainers_set_b`, v)
}

set_show_i <- function(p) {
    invisible(.Call(`_cppcontainers_set_show_i`, p))
}

set_show_d <- function(p) {
    invisible(.Call(`_cppcontainers_set_show_d`, p))
}

set_show_s <- function(p) {
    invisible(.Call(`_cppcontainers_set_show_s`, p))
}

set_show_b <- function(p) {
    invisible(.Call(`_cppcontainers_set_show_b`, p))
}

unordered_set_show_i <- function(p) {
    invisible(.Call(`_cppcontainers_unordered_set_show_i`, p))
}

unordered_set_show_d <- function(p) {
    invisible(.Call(`_cppcontainers_unordered_set_show_d`, p))
}

unordered_set_show_s <- function(p) {
    invisible(.Call(`_cppcontainers_unordered_set_show_s`, p))
}

unordered_set_show_b <- function(p) {
    invisible(.Call(`_cppcontainers_unordered_set_show_b`, p))
}

set_size_i <- function(x) {
    .Call(`_cppcontainers_set_size_i`, x)
}

set_size_d <- function(x) {
    .Call(`_cppcontainers_set_size_d`, x)
}

set_size_s <- function(x) {
    .Call(`_cppcontainers_set_size_s`, x)
}

set_size_b <- function(x) {
    .Call(`_cppcontainers_set_size_b`, x)
}

unordered_set_size_i <- function(x) {
    .Call(`_cppcontainers_unordered_set_size_i`, x)
}

unordered_set_size_d <- function(x) {
    .Call(`_cppcontainers_unordered_set_size_d`, x)
}

unordered_set_size_s <- function(x) {
    .Call(`_cppcontainers_unordered_set_size_s`, x)
}

unordered_set_size_b <- function(x) {
    .Call(`_cppcontainers_unordered_set_size_b`, x)
}

set_to_r_i <- function(x, use_n, n, reverse, use_from, from, use_to, to) {
    .Call(`_cppcontainers_set_to_r_i`, x, use_n, n, reverse, use_from, from, use_to, to)
}

set_to_r_d <- function(x, use_n, n, reverse, use_from, from, use_to, to) {
    .Call(`_cppcontainers_set_to_r_d`, x, use_n, n, reverse, use_from, from, use_to, to)
}

set_to_r_s <- function(x, use_n, n, reverse, use_from, from, use_to, to) {
    .Call(`_cppcontainers_set_to_r_s`, x, use_n, n, reverse, use_from, from, use_to, to)
}

set_to_r_b <- function(x, use_n, n, reverse, use_from, from, use_to, to) {
    .Call(`_cppcontainers_set_to_r_b`, x, use_n, n, reverse, use_from, from, use_to, to)
}

unordered_set_to_r_i <- function(x, n) {
    .Call(`_cppcontainers_unordered_set_to_r_i`, x, n)
}

unordered_set_to_r_d <- function(x, n) {
    .Call(`_cppcontainers_unordered_set_to_r_d`, x, n)
}

unordered_set_to_r_s <- function(x, n) {
    .Call(`_cppcontainers_unordered_set_to_r_s`, x, n)
}

unordered_set_to_r_b <- function(x, n) {
    .Call(`_cppcontainers_unordered_set_to_r_b`, x, n)
}

unordered_set_i <- function(v) {
    .Call(`_cppcontainers_unordered_set_i`, v)
}

unordered_set_d <- function(v) {
    .Call(`_cppcontainers_unordered_set_d`, v)
}

unordered_set_s <- function(v) {
    .Call(`_cppcontainers_unordered_set_s`, v)
}

unordered_set_b <- function(v) {
    .Call(`_cppcontainers_unordered_set_b`, v)
}

