# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
on:
  push:

name: R-CMD-check

permissions:
  actions: write
  contents: read

jobs:
  R-CMD-check:
    runs-on: macos-15
    name: macOS (R-devel, clang 16)

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes
      MAKE: make -j2
      LC_CTYPE: en_GB.UTF-8
      MallocNanoZone: 0
      UBSAN_OPTIONS: print_stacktrace=1
      _R_CHECK_FORCE_SUGGESTS_: FALSE
      _R_CHECK_INSTALL_DEPENDS_: true
      _R_CHECK_NO_RECOMMENDED_: true
      _R_CHECK_TIMINGS_: 10
      _R_CHECK_DEPRECATED_DEFUNCT_: true
      _R_CHECK_CODE_ASSIGN_TO_GLOBALENV_: true
      _R_CHECK_CODE_DATA_INTO_GLOBALENV_: true
      _R_CHECK_S3_METHODS_NOT_REGISTERED_: true
      _R_CHECK_NATIVE_ROUTINE_REGISTRATION_: true
      _R_CHECK_COMPILATION_FLAGS_: true
      _R_CHECK_THINGS_IN_TEMP_DIR_: true
      _R_CHECK_MATRIX_DATA_: TRUE
      _R_CHECK_BROWSER_NONINTERACTIVE_: true

    steps:
      - uses: actions/checkout@v4

      - name: Install system dependencies
        run: |
          brew update
          brew install gcc llvm@16 automake fribidi gettext pcre2 xz libgit2 
          brew install udunits cairo pkg-config tcl-tk jpeg libpng libtiff
          xcode-select --install || true

      - name: Configure clang 16
        run: |
          echo "CC=-L/opt/homebrew/opt/llvm@16/bin/clang" >> $GITHUB_ENV
          echo "CXX=-L/opt/homebrew/opt/llvm@16/bin/clang++" >> $GITHUB_ENV
          echo "LDFLAGS=-L/opt/homebrew/opt/llvm@16/lib/c++ -Wl,-rpath,/opt/homebrew/opt/llvm@16/lib/c++" >> $GITHUB_ENV
          echo "CPPFLAGS=-I/usr/local/opt/llvm@16/include" >> $GITHUB_ENV
          echo 'export PATH="/opt/homebrew/opt/llvm@16/bin:$PATH"' >> /Users/runner/.bash_profile

      - name: Download and compile R-devel
        run: |
          curl -O https://stat.ethz.ch/R/daily/R-devel.tar.gz
          tar -xzf R-devel.tar.gz
          mkdir r-devel-build
          cd r-devel-build
          sudo chown -R $(whoami) .
          ../R-devel/configure \
            --with-C23 \
            --enable-R-shlib \
            --enable-memory-profiling \
            --with-cairo \
            --with-jpeglib \
            --with-readline \
            --with-tcltk \
            --with-recommended-packages \
            --enable-RGBA
          make
          if [ $? -ne 0 ]; then
            echo "R compilation failed. Showing config.log:"
            cat config.log
            exit 1
          fi
          sudo make install

      - uses: r-lib/actions/setup-pandoc@v2

      - name: Configure sanitizers for package check
        run: |
          mkdir -p ~/.R
          echo "CFLAGS=-g -O2 -Wall -pedantic -Wconversion -Wno-sign-conversion -Wstrict-prototypes -fsanitize=address,undefined" > ~/.R/Makevars
          echo "CXXFLAGS=-g -O2 -Wall -pedantic -Wconversion -Wno-sign-conversion -fsanitize=address,undefined" >> ~/.R/Makevars
          echo "LDFLAGS=-fsanitize=address,undefined" >> ~/.R/Makevars

      - name: Install package dependencies
        run: |
          R -e 'install.packages("remotes")'
          R -e 'remotes::install_deps(dependencies = TRUE)'
          R -e 'install.packages("rcmdcheck")'

      - name: Check package
        run: |
          R -e 'rcmdcheck::rcmdcheck(args = c("--no-manual", "--as-cran"), error_on = "warning", check_dir = "check")'

      - name: Upload check results
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: ${{ runner.os }}-r-devel-results
          path: check
